In [28]:
import pandas as pd
from sklearn.ensemble import BaggingClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import f1_score, mean_absolute_error

In [2]:
wine_data = pd.read_csv('wineQualityReds.csv', index_col=0)
wine_data.head()

,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,quality
1,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
2,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
5,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
wine_data['quality'] = wine_data['quality'].apply(lambda x: 1 if x >= 6 else 0)
X = wine_data.drop('quality', axis=1)
y = wine_data['quality']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
lg = LogisticRegression(max_iter=1000)
lg.fit(X_train, y_train)

y_lg_pred = lg.predict(X_test)

In [6]:
dt = DecisionTreeClassifier(random_state=42, max_depth=10)
dt.fit(X_train, y_train)

y_dt_pred = dt.predict(X_test)

In [17]:
print("LogisticRegression F1-score\n", round(f1_score(y_test, y_lg_pred), 3))
print("DecisionTreeClassifier F1-score\n", round(f1_score(y_test, y_dt_pred), 3))

ValueError: Found input variables with inconsistent numbers of samples: [152, 480]

In [8]:
dt = DecisionTreeClassifier(random_state=42, max_depth=10)
bc = BaggingClassifier(estimator=dt, n_estimators=1500, random_state=42)
bc.fit(X_train, y_train)

y_bc_pred = bc.predict(X_test)
print("BaggingClassifier F1-score\n", round(f1_score(y_test, y_bc_pred), 3))

BaggingClassifier F1-score
 0.819

## Случайный лес

In [9]:
house_data = pd.read_csv('boston.csv')
house_data.head()

,crim_rate,zn,business,river,nit_oxiden,rooms,age,dist,highways_index,tax,pup_per_teaс,lower,target
0,"0,00632",18,"2,31",0,"0,538","6,575","65,2","4,09",1,296,"15,3","4,98",24
1,"0,02731",0,"7,07",0,"0,469","6,421","78,9","4,9671",2,242,"17,8","9,14","21,6"
2,"0,02729",0,"7,07",0,"0,469","7,185","61,1","4,9671",2,242,"17,8","4,03","34,7"
3,"0,03237",0,"2,18",0,"0,458","6,998","45,8","6,0622",3,222,"18,7","2,94","33,4"
4,"0,06905",0,"2,18",0,"0,458","7,147","54,2","6,0622",3,222,"18,7","5,33","36,2"

In [15]:
for col in house_data.columns:
    if house_data[col].dtype == 'object':
        house_data[col] = pd.to_numeric(house_data[col].str.replace(',', '.', regex=False))
X = house_data.drop(columns=['target'])
y = house_data['target']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=13)

In [18]:
print("Среднее значение медианных цен:", round(y_train.mean(), 2))

Среднее значение медианных цен: 22.77

In [23]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

y_pred = lin_reg.predict(X_test)

print('MAE:', round(mean_absolute_error(y_test, y_pred), 2))

MAE: 3.72

In [27]:
dt = DecisionTreeRegressor(random_state=13)
dt.fit(X_train, y_train)

y_train_pred = dt.predict(X_train)
y_test_pred = dt.predict(X_test)

print('MAE train:', round(mean_absolute_error(y_train, y_train_pred), 2))
print('MAE test:', round(mean_absolute_error(y_test, y_test_pred), 2))

MAE train: 0.0
MAE test: 2.84

In [29]:
rf_3 = RandomForestRegressor(n_estimators=3, random_state=13)
rf_10 = RandomForestRegressor(n_estimators=10, random_state=13)
rf_100 = RandomForestRegressor(n_estimators=100, random_state=13)
rf_500 = RandomForestRegressor(n_estimators=500, random_state=13)

rf_3.fit(X_train, y_train)
rf_10.fit(X_train, y_train)
rf_100.fit(X_train, y_train)
rf_500.fit(X_train, y_train)

y_3_pred = rf_3.predict(X_test)
y_10_pred = rf_10.predict(X_test)
y_100_pred = rf_100.predict(X_test)
y_500_pred = rf_500.predict(X_test)

print('MAE 3:', round(mean_absolute_error(y_test, y_3_pred), 2))
print('MAE 10:', round(mean_absolute_error(y_test, y_10_pred), 2))
print('MAE 100:', round(mean_absolute_error(y_test, y_100_pred), 2))
print('MAE 500:', round(mean_absolute_error(y_test, y_500_pred), 2))

MAE 3: 2.93
MAE 10: 2.42
MAE 100: 2.24
MAE 500: 2.23