In [30]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score, adjusted_rand_score, homogeneity_score, completeness_score

In [7]:
X_test = pd.read_csv('data/test.txt', sep='\s+', header=None)
X_train = pd.read_csv('data/train.txt', sep='\s+', header=None)
y_train = pd.read_csv('data/train_labels.txt', header=None)
y_test = pd.read_csv('data/test_labels.txt', header=None)

   0
0  5
1  5
2  5
3  5
4  5

In [8]:
X = pd.concat([X_train, X_test])
y = pd.concat([y_train, y_test])
X.shape

(10299, 561)

In [10]:
y.nunique()

0    6
dtype: int64

In [12]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[0][0]

np.float64(0.21053385417675513)

In [15]:
def get_metric_score(cluster_num, X, metric):
    k_means = KMeans(n_clusters=cluster_num, random_state=42)
    k_means.fit(X)
    metric_score = metric(X, k_means.predict(X))
    return metric_score

In [17]:
metric_res = {}

for metric in [silhouette_score, calinski_harabasz_score, davies_bouldin_score]:
    if metric.__name__ not in metric_res:
        metric_res[metric.__name__] = {'metric': [], 'cluster': []}
    for cluster_num in range(2, 10):
        metric_res[metric.__name__]['metric'].append(get_metric_score(cluster_num, X_scaled, metric))
        metric_res[metric.__name__]["cluster"].append(cluster_num)
    metric_res[metric.__name__]['df'] = pd.DataFrame(metric_res[metric.__name__])

In [24]:
k_means = KMeans(n_clusters=6, init='random', random_state=42)
k_means.fit(X_scaled)

y_pred = k_means.predict(X_scaled)

print('Hom:', round(homogeneity_score(y[0].values, y_pred), 2))
print('Com:', round(completeness_score(y[0].values, y_pred), 2))
print('Ran:', round(adjusted_rand_score(y[0].values, y_pred), 2))

Hom: 0.54
Com: 0.58
Ran: 0.42

In [25]:
ct = pd.crosstab(y[0], y_pred)

In [26]:
k_means = KMeans(n_clusters=2, init='random', random_state=42)
k_means.fit(X_scaled)

y_pred = k_means.predict(X_scaled)

print('Hom:', round(homogeneity_score(y[0].values, y_pred), 2))
print('Com:', round(completeness_score(y[0].values, y_pred), 2))
print('Ran:', round(adjusted_rand_score(y[0].values, y_pred), 2))

Hom: 0.38
Com: 0.98
Ran: 0.33

In [27]:
pd.crosstab(y[0], y_pred)

col_0     0     1
0
1      1722     0
2      1536     8
3      1406     0
4         3  1774
5         0  1906
6        12  1932

In [32]:
em = AgglomerativeClustering(n_clusters=2)
y_pred = em.fit_predict(X_scaled)

print('Hom:', round(homogeneity_score(y[0].values, y_pred), 2))
print('Com:', round(completeness_score(y[0].values, y_pred), 2))
print('Ran:', round(adjusted_rand_score(y[0].values, y_pred), 2))

Hom: 0.39
Com: 1.0
Ran: 0.33